# Generated by Django 4.2.7 on 2023-11-30 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('API', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=200)),
                ('Auth', models.CharField(blank=True, max_length=20, null=True)),
                ('HTTPS', models.BooleanField(default=False)),
                ('Cors', models.BooleanField(default=False)),
                ('Link', models.URLField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
        ),
    ]
